package botserver

import (
  pg "leaddits/internal/pkg/pg"
)

// Update represents a Telegram incoming webhook update
type Update struct {
  Message struct {
    Chat struct {
      ID int64 `json:"id"`
    } `json:"chat"`
    From struct {
      Username string `json:"username"`
    } `json:"from"`
    Text string `json:"text"`
  } `json:"message"`
}

// Listing represents the enriched marketplace data usually
// generated by your AI or search logic.
type Listing struct {
  Title       string   `json:"title"`
  Price       string   `json:"price"` // Raw price string from listing
  Location    *string  `json:"location"`
  Condition   string   `json:"condition"`
  DealScore   *float64 `json:"deal_score"`
  SellerNotes []string `json:"seller_notes"`
  Verdict     string   `json:"verdict"`
  WatchOut    string   `json:"watch_out"`
  URL         string   `json:"url"`
}

// MarketplaceSearch represents the collection of results
// for a specific user query.
type MarketplaceSearch struct {
  Query    string    `json:"query"`
  Listings []Listing `json:"listings"`
}

// PairedResult is a helper struct used during the formatting process
// to link a processed Listing with its original Database Post.
type PairedResult struct {
  Listing Listing
  Post    pg.RedditPost
}

